project_id = "tgcmhmcgxzabimgnzsiu"

[functions.open-pack]
verify_jwt = false

[functions.buy-gem-card]
verify_jwt = false

[functions.claim-starter-pack]
verify_jwt = false

[functions.quicksell-card]
verify_jwt = false

[functions.redeem-locker-code]
verify_jwt = false

[functions.refresh-auction]
verify_jwt = false

[functions.buy-auction-card]
verify_jwt = false

[functions.complete-gem-task]
verify_jwt = false
