// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-rows.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/db.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
var ALLOWED_TABLES = [
  "player_cards",
  "teams",
  "team_players",
  "runs",
  "run_players",
  "run_rank_rewards",
  "domination_games",
  "domination_game_players",
  "challenges",
  "gem_tasks",
  "gem_tiers",
  "gem_market_listings",
  "dynamic_duos",
  "collections",
  "badges",
  "locker_codes",
  "evo_paths",
  "location_accounts",
  "location_post_templates"
];
function db(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function ok(payload) {
  return {
    content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
    structuredContent: payload
  };
}
function fail(message) {
  return { content: [{ type: "text", text: message }], isError: true };
}
async function adminClient(ctx) {
  if (!ctx.isAuthenticated()) return { error: fail("Not authenticated. Sign in to this app first.") };
  const client = db(ctx);
  const { data, error } = await client.rpc("has_role", { _user_id: ctx.getUserId(), _role: "admin" });
  if (error) return { error: fail(`Could not verify admin role: ${error.message}`) };
  if (!data) return { error: fail("Admin role required for this tool.") };
  return { client };
}
async function userClient(ctx) {
  if (!ctx.isAuthenticated()) return { error: fail("Not authenticated. Sign in to this app first.") };
  return { client: db(ctx) };
}

// src/lib/mcp/tools/list-rows.ts
var list_rows_default = defineTool({
  name: "list_rows",
  title: "List rows",
  description: "Read rows from a GTeam Infinite table (players, teams, runs, dominations, challenges, gem tasks, duos, collections, badges, locker codes, evo paths, media accounts). Supports a text search and column selection.",
  inputSchema: {
    table: z.enum(ALLOWED_TABLES).describe("Table to read."),
    search: z.string().optional().describe("Case-insensitive match against the name/title column."),
    columns: z.string().optional().describe("Comma-separated columns. Defaults to all."),
    limit: z.number().int().min(1).max(500).optional().describe("Max rows (default 100).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table, search, columns, limit }, ctx) => {
    const { client, error } = await userClient(ctx);
    if (error) return error;
    let query = client.from(table).select(columns || "*").limit(limit ?? 100);
    if (search) {
      const nameCol = table === "gem_tasks" ? "title" : table === "domination_games" ? "opponent_name" : "name";
      query = query.ilike(nameCol, `%${search}%`);
    }
    const { data, error: dbError } = await query;
    if (dbError) return fail(dbError.message);
    return ok({ table, count: data?.length ?? 0, rows: data ?? [] });
  }
});

// src/lib/mcp/tools/create-rows.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var create_rows_default = defineTool2({
  name: "create_rows",
  title: "Create rows",
  description: "Admin only. Insert new rows into a GTeam Infinite table. Each row is an object of column/value pairs; call list_rows first to learn the shape. Returns the inserted rows.",
  inputSchema: {
    table: z2.enum(ALLOWED_TABLES).describe("Table to insert into."),
    rows: z2.array(z2.record(z2.string(), z2.any())).describe("Rows to insert as column/value objects.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ table, rows }, ctx) => {
    const { client, error } = await adminClient(ctx);
    if (error) return error;
    if (!rows.length) return fail("No rows supplied.");
    const { data, error: dbError } = await client.from(table).insert(rows).select();
    if (dbError) return fail(dbError.message);
    return ok({ table, inserted: data?.length ?? 0, rows: data ?? [] });
  }
});

// src/lib/mcp/tools/update-rows.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var update_rows_default = defineTool3({
  name: "update_rows",
  title: "Update rows",
  description: "Admin only. Patch existing rows matched by a column value (defaults to `name`, use `title` for gem tasks). Only the fields you send are written; everything else is left untouched.",
  inputSchema: {
    table: z3.enum(ALLOWED_TABLES).describe("Table to update."),
    match_column: z3.string().optional().describe("Column used to find the row. Defaults to `name`."),
    updates: z3.array(
      z3.object({
        match: z3.string().describe("Value of the match column, e.g. the player name."),
        patch: z3.record(z3.string(), z3.any()).describe("Columns to write.")
      })
    ).describe("One entry per row to patch.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ table, match_column, updates }, ctx) => {
    const { client, error } = await adminClient(ctx);
    if (error) return error;
    const col = match_column || (table === "gem_tasks" ? "title" : "name");
    const applied = [];
    const notFound = [];
    const failed = [];
    for (const { match, patch } of updates) {
      const { data, error: dbError } = await client.from(table).update(patch).ilike(col, match).select("id");
      if (dbError) failed.push({ match, error: dbError.message });
      else if (!data?.length) notFound.push(match);
      else applied.push(match);
    }
    return ok({ table, match_column: col, updated: applied.length, applied, not_found: notFound, failed });
  }
});

// src/lib/mcp/tools/delete-rows.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var delete_rows_default = defineTool4({
  name: "delete_rows",
  title: "Delete rows",
  description: "Admin only. Permanently delete rows matched by id. Destructive \u2014 confirm with the user before calling.",
  inputSchema: {
    table: z4.enum(ALLOWED_TABLES).describe("Table to delete from."),
    ids: z4.array(z4.string()).describe("Row ids (uuid) to delete.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ table, ids }, ctx) => {
    const { client, error } = await adminClient(ctx);
    if (error) return error;
    if (!ids.length) return fail("No ids supplied.");
    const { data, error: dbError } = await client.from(table).delete().in("id", ids).select("id");
    if (dbError) return fail(dbError.message);
    return ok({ table, deleted: data?.length ?? 0, ids: (data ?? []).map((r) => r.id) });
  }
});

// src/lib/mcp/tools/create-players.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var StatSchema = z5.number().min(0).max(150);
var create_players_default = defineTool5({
  name: "create_players",
  title: "Create players",
  description: 'Admin only. Create player cards. Gem tier and team are resolved by name, so you can say `gem_tier: "Diamond"` instead of an id. Ratings accept decimals.',
  inputSchema: {
    players: z5.array(
      z5.object({
        name: z5.string().describe("Card name (must be unique-ish; existing names are reported back)."),
        gem_tier: z5.string().optional().describe("Gem tier name, e.g. Emerald / Diamond."),
        team: z5.string().optional().describe("Team name to attach the card to."),
        position1: z5.string().optional(),
        position2: z5.string().optional(),
        rating: z5.number().optional().describe("Overall rating, decimals allowed (e.g. 87.4)."),
        stat_3pt: StatSchema.optional(),
        stat_mid: StatSchema.optional(),
        stat_fin: StatSchema.optional(),
        stat_dnk: StatSchema.optional(),
        stat_ast: StatSchema.optional(),
        stat_stl: StatSchema.optional(),
        stat_reb: StatSchema.optional(),
        stat_blk: StatSchema.optional(),
        stat_int: StatSchema.optional(),
        market_value: z5.number().optional(),
        social_handle: z5.string().optional(),
        card_animation: z5.string().optional().describe("e.g. none / pulse / shimmer / glow.")
      })
    ).describe("Players to create.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ players }, ctx) => {
    const { client, error } = await adminClient(ctx);
    if (error) return error;
    if (!players.length) return fail("No players supplied.");
    const [{ data: tiers }, { data: teams }] = await Promise.all([
      client.from("gem_tiers").select("id, name"),
      client.from("teams").select("id, name")
    ]);
    const tierByName = new Map((tiers ?? []).map((t) => [String(t.name).toLowerCase(), t.id]));
    const teamByName = new Map((teams ?? []).map((t) => [String(t.name).toLowerCase(), t.id]));
    const unresolved = [];
    const rows = players.map((p) => {
      const { gem_tier, team, ...rest } = p;
      const gem_tier_id = gem_tier ? tierByName.get(gem_tier.toLowerCase()) : void 0;
      const team_id = team ? teamByName.get(team.toLowerCase()) : void 0;
      if (gem_tier && !gem_tier_id) unresolved.push(`gem tier "${gem_tier}" (${p.name})`);
      if (team && !team_id) unresolved.push(`team "${team}" (${p.name})`);
      return { ...rest, gem_tier_id: gem_tier_id ?? null, team_id: team_id ?? null };
    });
    const { data, error: dbError } = await client.from("player_cards").insert(rows).select("id, name, rating");
    if (dbError) return fail(dbError.message);
    return ok({ created: data?.length ?? 0, players: data ?? [], unresolved_references: unresolved });
  }
});

// src/lib/mcp/tools/set-roster.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z6 } from "npm:zod@^3.25.76";
var set_roster_default = defineTool6({
  name: "set_roster",
  title: "Set a roster",
  description: "Admin only. Replace the roster of a team, a run, or a domination game with the given player card names (in slot order). Player names must already exist \u2014 create them first with create_players.",
  inputSchema: {
    target: z6.enum(["team", "run", "domination"]).describe("What kind of roster to set."),
    name: z6.string().describe("Team name, run name, or domination opponent name."),
    players: z6.array(z6.string()).describe("Player card names, in slot order (usually 3).")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ target, name, players }, ctx) => {
    const { client, error } = await adminClient(ctx);
    if (error) return error;
    const config = {
      team: { parent: "teams", nameCol: "name", child: "team_players", fk: "team_id", slots: true },
      run: { parent: "runs", nameCol: "name", child: "run_players", fk: "run_id", slots: false },
      domination: {
        parent: "domination_games",
        nameCol: "opponent_name",
        child: "domination_game_players",
        fk: "domination_game_id",
        slots: true
      }
    }[target];
    const { data: parent, error: parentErr } = await client.from(config.parent).select("id").ilike(config.nameCol, name).maybeSingle();
    if (parentErr) return fail(parentErr.message);
    if (!parent) return fail(`No ${target} named "${name}".`);
    const { data: cards, error: cardErr } = await client.from("player_cards").select("id, name").in("name", players);
    if (cardErr) return fail(cardErr.message);
    const byName = new Map((cards ?? []).map((c) => [String(c.name).toLowerCase(), c.id]));
    const missing = players.filter((p) => !byName.has(p.toLowerCase()));
    if (missing.length) return fail(`Unknown player cards: ${missing.join(", ")}`);
    const { error: delErr } = await client.from(config.child).delete().eq(config.fk, parent.id);
    if (delErr) return fail(delErr.message);
    const rows = players.map((p, idx) => ({
      [config.fk]: parent.id,
      player_card_id: byName.get(p.toLowerCase()),
      ...config.slots ? { slot: idx + 1 } : {}
    }));
    const { error: insErr } = await client.from(config.child).insert(rows);
    if (insErr) return fail(insErr.message);
    return ok({ target, name, roster: players, size: rows.length });
  }
});

// src/lib/mcp/tools/get-diagnostics.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.25.0";
var get_diagnostics_default = defineTool7({
  name: "get_diagnostics",
  title: "Get content diagnostics",
  description: "Reports incomplete content: unrated players, teams with fewer than 3 cards, runs with no opponent roster, and domination games with no roster. Call this first when asked to fill gaps.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    const { client, error } = await userClient(ctx);
    if (error) return error;
    const [players, teams, teamPlayers, runs, runPlayers, doms, domPlayers] = await Promise.all([
      client.from("player_cards").select("id, name, rating, stat_3pt, stat_fin, stat_mid"),
      client.from("teams").select("id, name"),
      client.from("team_players").select("team_id"),
      client.from("runs").select("id, name"),
      client.from("run_players").select("run_id"),
      client.from("domination_games").select("id, road_name, opponent_name"),
      client.from("domination_game_players").select("domination_game_id")
    ]);
    const countBy = (rows, key) => {
      const map = /* @__PURE__ */ new Map();
      (rows ?? []).forEach((r) => map.set(r[key], (map.get(r[key]) ?? 0) + 1));
      return map;
    };
    const teamCounts = countBy(teamPlayers.data, "team_id");
    const runCounts = countBy(runPlayers.data, "run_id");
    const domCounts = countBy(domPlayers.data, "domination_game_id");
    const unrated = (players.data ?? []).filter((p) => !p.rating && !p.stat_3pt && !p.stat_fin && !p.stat_mid).map((p) => p.name);
    const payload = {
      unrated_players: unrated,
      incomplete_team_rosters: (teams.data ?? []).map((t) => ({ name: t.name, cards: teamCounts.get(t.id) ?? 0 })).filter((t) => t.cards < 3),
      incomplete_runs: (runs.data ?? []).map((r) => ({ name: r.name, opponents: runCounts.get(r.id) ?? 0 })).filter((r) => r.opponents < 3),
      incomplete_domination_paths: (doms.data ?? []).map((d) => ({
        road: d.road_name,
        opponent: d.opponent_name,
        cards: domCounts.get(d.id) ?? 0
      })).filter((d) => d.cards < 3)
    };
    return ok({
      ...payload,
      summary: {
        unrated_players: payload.unrated_players.length,
        incomplete_team_rosters: payload.incomplete_team_rosters.length,
        incomplete_runs: payload.incomplete_runs.length,
        incomplete_domination_paths: payload.incomplete_domination_paths.length
      }
    });
  }
});

// src/lib/mcp/tools/get-system-docs.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/systemDocs.ts
var SYSTEM_DOCS_MARKDOWN = `# G-Team Infinite \u2014 System Reference

## Overview
A collectible-card sports sim. Players (cards) belong to **Teams**, which appear in
**Dominations** (3v3 boss-style matchups) and **Runs** (ladder of 3v3 opponent sets).
Cards are acquired via **Packs**, the **Gem Market**, the **Auction House**, and
**Locker Codes**. Cards evolve via **Evo Paths**, gain **Badges** and **Signature Traits**,
and pair into **Dynamic Duos** for stat boosts. Progress is tracked via **Collections**,
**Sub-Collections**, and **Challenges**. A **Social Feed** + **League History** page
present narrative events authored as **Storylines**.

## Entities

### player_cards
The atomic unit. Fields include name, archetype, overall, per-stat ratings,
rarity, image_url, collection_id/sub_collection_id, plus evo lineage pointers.

### teams + team_players
A roster of player_cards. Categories: \`domination\`, \`run\`, \`challenge\`.
\`unlock_cost_gems\` gates Domination teams; Run teams ladder by rank.

### runs + run_players + run_rank_rewards
A **Run** is a 3v3 ladder. Each rank tier has opponent rosters (run_players)
and rewards (run_rank_rewards: gems, packs, specific cards).

### dominations (domination_games + domination_game_players)
Boss matchups. Beating a Domination team usually grants its signature card.

### challenges + challenge_completions
Win-condition objectives (e.g., "win with 3 sharpshooters"). Reward packs/gems/cards.

### packs + pack_odds + pack_players
A pack has odds per rarity and a pool of eligible players. Opens 1 card per call
via the \`open-pack\` edge function.

### gem_tiers + gem_market_listings
Tiered storefront. Buying a gem-market card auto-syncs it into the tier's collection
(see \`sync_gem_tier_collection\` trigger).

### auction_listings
User-driven marketplace. Bid/buy-now via \`buy-auction-card\` edge function.

### locker_codes + locker_code_redemptions
Promo codes redeemable for packs/gems/cards via \`redeem-locker-code\`.

### gem_tasks + gem_task_completions
Real-world or in-app tasks awarding gems on cooldown.

### dynamic_duos
Pairs of player_cards. When both are on the same lineup, both receive stat boosts.

### badges + signature_traits + player_card_(badges|traits)
Modifiers attached to cards. Badges are universal; signature_traits are unique flavor.

### evo_paths + user_evo_progress
Upgrade lanes. Hitting milestones evolves a card into its next form.

### collections + sub_collections + user_collections + user_collection_claims
Hierarchical sets. Completing one awards rewards. Gem-market collections are
auto-managed (do not edit manually).

### social_posts + social_creators
Tweet-style feed. \`is_headline\` + \`headline_rank\` promote a post to the
**League History** hero. Linked to storylines via storyline_entities.

### storylines + storyline_entities
Narrative arcs that bundle players, locker codes, and social posts into one
atomically-imported package (\`import-storyline-bundle\` edge function).

### profiles + user_roles
\`user_roles\` is the single source of truth for admin/player permissions
(checked via \`has_role()\`). Never store role on profile.

## Game Loop (TL;DR)
1. User opens **Packs** / buys from **Gem Market** / wins **Auctions** \u2192 gains cards.
2. Builds lineups \u2192 plays **Runs** (3v3 ladder) and **Dominations** (boss 3v3 / 5v5).
3. Completes **Challenges** + **Gem Tasks** for currency.
4. Currency feeds back into Packs, evolves cards (**Evo Paths**), pairs **Duos**.
5. **Social Posts** + **Storylines** narrate the meta on the **League History** page.

## Conventions (when authoring with ChatGPT)
- **Names must be unique** within an entity type \u2014 collisions are rejected at import.
- **Archetypes, gem tiers, opponent team names** must match values already in the DB
  (the snapshot below lists them).
- **Roster references** use player names exactly \u2014 the importer resolves to IDs.
- **Cards** are styled \`aspect-[3/4] w-full\`, image_url should match.
- **Rewards** are JSON: \`{ gems?: number, pack_id?: uuid, card_id?: uuid }\`.
- **Storylines** can bundle players + locker_codes + social_posts in one JSON.
- **Ratings are decimals** (numeric, e.g. \`87.4\`) \u2014 preserve to one decimal place. Do not round.

## Diagnostics block (read this FIRST)
The snapshot includes a top-level \`diagnostics\` object listing what is incomplete:
- \`diagnostics.unrated_players\` \u2014 players with no rating or all-zero stats. When asked
  to "rate unrated players", iterate this list exclusively.
- \`diagnostics.incomplete_team_rosters\` \u2014 teams with fewer than 3 player slots filled
  (category included so you know whether it's a domination / run / challenge team).
- \`diagnostics.incomplete_runs\` \u2014 runs missing opponent cards, milestones, or target_score.
- \`diagnostics.incomplete_domination_paths\` \u2014 domination games whose roster has < 3 cards.

When the user gives a broad brief like "finish the missing rosters" or "rate the unrated
players", emit JSON ONLY for the items listed in the matching diagnostics array.

## How to use the snapshot below with ChatGPT
1. Paste the README + the JSON snapshot as a single system message in ChatGPT.
2. Ask for content (e.g., "Rate every player in diagnostics.unrated_players" or
   "Generate 10 new sharpshooters for 'East Coast Era'"). ChatGPT will respect existing
   names + enums and target only what's incomplete.
3. Paste its JSON output into the matching Admin page's "AI Import / Export" tab
   (use **Update existing** mode for edits, **Create** mode for new content).
`;

// src/lib/mcp/tools/get-system-docs.ts
var get_system_docs_default = defineTool8({
  name: "get_system_docs",
  title: "Get system reference",
  description: "Returns the GTeam Infinite system reference: how players, teams, runs, dominations, packs, gems, evolutions and the social feed connect. Read this before creating or editing content.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({ content: [{ type: "text", text: SYSTEM_DOCS_MARKDOWN }] })
});

// src/lib/mcp/index.ts
var projectRef = "tgcmhmcgxzabimgnzsiu";
var mcp_default = defineMcp({
  name: "gteam-infinite-hub",
  title: "GTeam Infinite Hub",
  version: "0.1.0",
  instructions: "Tools for building and editing GTeam Infinite content. Start with get_system_docs for the data model and get_diagnostics for gaps. Use list_rows to inspect current data, create_players / create_rows to add content, update_rows to patch existing rows by name, set_roster to fill team / run / domination rosters, and delete_rows only after confirming with the user. All writes require an admin account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_system_docs_default,
    get_diagnostics_default,
    list_rows_default,
    create_players_default,
    create_rows_default,
    update_rows_default,
    set_roster_default,
    delete_rows_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
